version: "3"
services:
  postgres:
    build: "./db"
    volumes:
      - "./db/initdb.d:/docker-entrypoint-initdb.d"
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_PASSWORD=root_password123
      - DB_BLOCKSCOUT_PASSWORD=blockscout_password123
  blockscout:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    restart: always
    build: "./blockscout"
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://blockscout_user:blockscout_password123@postgres:5432/blockscout_testing?ssl=false
      ECTO_USE_SSL: false
      SECRET_KEY_BASE: 56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: 'true'
      ETHEREUM_JSONRPC_VARIANT: geth
      ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545
      NETWORK: "Kava Ethereum Co-Chain"
      LOGO: "/images/kava-logo.png"
      LOGO_TEXT: "Ethereum Co-Chain"
      COIN: KAVA
volumes:
  pgdata:
